const varsayilanLigler = [
  "İngiltere Premier League",
  "İspanya La Liga",
  "Almanya Bundesliga",
  "İtalya Serie A",
  "Fransa Ligue 1",
  "Hollanda Eredivisie",
  "Portekiz Primeira Liga",
  "Rusya Premier Liga",
  "Japonya J1 League",
  "Güney Kore K League 1",
  "Çin Super League",
  "UEFA Şampiyonlar Ligi",
  "UEFA Avrupa Ligi",
  "UEFA Avrupa Konferans Ligi",
  "UEFA Süper Kupa",
  "UEFA Uluslar Ligi",
  "UEFA EURO Finalleri",
  "EURO Elemeleri",
  "Dünya Kupası Avrupa Elemeleri",
  "FIFA Dünya Kupası Finalleri",
  "İngiltere Championship Playoff",
  "EURO Playoff"
];
